POST http://localhost:8080/api/v1/articlelist
Content-Type: application/json;utf8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU0VSX1RBUkdFVEdST1VQUyI6WyJBX0dST1VQIl0sIlVTRVJOQU1FIjoi7J2066eQ64WEIiwiVVNFUl9JRCI6MiwiVVNFUl9ST0xFIjoiUk9MRV9BRE1JTiJ9.EW_MR-tdr__NQQEXpIn3G9GsHXYvgpiPoUCt0__-z9I

{"itemPerPage" : 5, "currentPage" : 0}

###