GET http://localhost:8080/api/info/userinfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU0VSX1RBUkdFVEdST1VQUyI6WyJCX0dST1VQIiwiQ19HUk9VUCJdLCJVU0VSTkFNRSI6IuydtOunkOuFhCIsIlVTRVJfSUQiOjIsIlVTRVJfUk9MRSI6IlJPTEVfVVNFUiJ9.bjluOAI9B9J9B1P8_wsi4BqaxlMTnHb60JuQyF0ZVvU

###