GET http://localhost:8080/api/v1/article?id=5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVU0VSX1RBUkdFVEdST1VQUyI6WyJCX0dST1VQIiwiQ19HUk9VUCJdLCJVU0VSTkFNRSI6IuydtOunkOuFhCIsIlVTRVJfSUQiOjEsIlVTRVJfUk9MRSI6IlJPTEVfVVNFUiJ9.Bfq7A3d_-twc4YnoMNO3NBVflojkzIiWrZ5xNRcrS38

###
